pid = /run/stunnel.pid
debug = 7
output = /var/log/stunnel4/stunnel.log

[nfs-client]
client = yes
accept = 127.0.0.1:2049
connect = nas-san.vagrant-dummy-ops.lab:2363
checkHost = nas-san.vagrant-dummy-ops.lab
cert = /etc/ssl/localcerts/vagrant_apache.crt
key = /etc/ssl/localcerts/vagrant_apache.key
CAfile = /usr/local/share/ca-certificates/vagrant_ca.crt
sslVersion = TLSv1.3
verify = 2
