---
- name: Generate SSHA hash for nslcd_guest password using slappasswd
  ansible.builtin.command:
    cmd: 'slappasswd -s "{{ dummy_nslcd_password }}"'
  register: slappasswd_hash
  changed_when: false
  no_log: true

- name: Create nslcd_guest service account
  ansible.builtin.ldap_entry:
    dn: cn=nslcd_guest,ou=services,ou=it,dc=vagrant-dummy-ops,dc=lab
    objectClass:
      - simpleSecurityObject
      - organizationalRole
    attributes:
      cn: nslcd_guest
      userPassword: "{{ slappasswd_hash.stdout }}"
      description: Service account for nslcd
    server_uri: "ldaps://openldap.vagrant-dummy-ops.lab"
    bind_dn: cn=admin,dc=vagrant-dummy-ops,dc=lab
    bind_pw: "{{ root_ldap_password }}"
  no_log: true
