[libdefaults]
    default_realm = VAGRANT-DUMMY-OPS.LAB
    dns_lookup_realm = false
    dns_lookup_kdc = false
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true

[realms]
    VAGRANT-DUMMY-OPS.LAB = {
        kdc = kdc.vagrant-dummy-ops.lab
        admin_server = kdc.vagrant-dummy-ops.lab
    }

[domain_realm]
    .vagrant-dummy-ops.lab = VAGRANT-DUMMY-OPS.LAB
    vagrant-dummy-ops.lab = VAGRANT-DUMMY-OPS.LAB
