defaults {
    user_friendly_names yes
    find_multipaths yes
    max_fds 8192
}

blacklist {
    devnode "^sd[a-a]$"
}

devices {
    device {
        vendor "LIO-ORG"
        product "san_disk"
        path_grouping_policy multibus
        prio alua
        path_checker tur
    }
}

multipaths {
    multipath {
        wwid "360014051bb48186c7884e4c90d5e8cb8"
        alias san_disk_salle1
    }

    multipath {
        wwid "360014059df733d3d7c5413bbe08b90e0"
        alias san_disk_salle2
    }

}
