allow_anon_ssl=NO
allow_writeable_chroot=YES
anon_upload_enable=NO
anonymous_enable=NO
connect_from_port_20=YES
dirmessage_enable=YES
hide_ids=YES
listen=YES
listen_ipv6=NO
local_enable=YES
local_root=/data/dns_manager/
local_umask=022
log_ftp_protocol=YES
pam_service_name=vsftpd
rsa_cert_file=/etc/ssl/certs/vagrant_vsftp.pem
rsa_private_key_file=/etc/ssl/private/vagrant_vsftp.key
ssl_enable=YES
ssl_sslv3=YES
use_localtime=YES
userlist_deny=NO
userlist_enable=YES
write_enable=YES
xferlog_enable=YES
xferlog_file=/var/log/vsftpd.log
xferlog_std_format=YES
# Enable Passive Mode
pasv_enable=YES
# Set the passive port range
pasv_min_port=10000
pasv_max_port=10100
