---
- name: Check if stunnel4 installed
  ansible.builtin.stat:
    path: '/etc/init.d/stunnel4'
  register: stunnel4_path

- block:
  - name: Stop stunnel4
    ansible.builtin.service:
      name: stunnel4
      state: stopped

  - name: Ensure stunnel4 package is removed and purge done
    ansible.builtin.apt:
      name: stunnel4
      state: absent
      purge: yes

  - name: Remove stunnel4 certificate files
    ansible.builtin.file:
      path: '/etc/ssl/localcerts/{{ item }}'
      state: absent
    loop:
      - vagrant_stunnel4-client.crt
      - vagrant_stunnel4-client.key
  when: "stunnel4_path.stat.exists == true"
