---
- name: Untrust on Debian
  ansible.builtin.include_tasks:
    file: untrust_on_debian.yml
    apply:
      tags:
        - untrust
  tags:
    - untrust
  when: ansible_distribution == 'Debian'

- name: Untrust on Rhel
  ansible.builtin.include_tasks:
    file: untrust_on_rhel.yml
    apply:
      tags:
        - untrust
  tags:
    - untrust
  when: ansible_distribution == 'Rocky'
