---
- name: Remove unbound
  ansible.builtin.apt:
    name: unbound
    state: absent
    purge: yes

- name: Update resolv.conf to default set on virtualbox
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    regexp: '^nameserver'
    line: 'nameserver 10.0.2.3'
