---
- name: Add dummy users on Debian
  ansible.builtin.include_tasks:
    file: ldapadd_on_debian.yml
    apply:
      tags:
        - install
  tags:
    - install
  when: ansible_distribution == 'Debian'

- name: Add dummy users on Rhel
  ansible.builtin.include_tasks:
    file: ldapadd_on_rhel.yml
    apply:
      tags:
        - install
  tags:
    - install
  when: ansible_distribution == 'Rocky'
