[active]
dns1 ansible_host=192.168.1.200
dns2 ansible_host=192.168.1.201
vsftp ansible_host=192.168.1.202
nas-san ansible_host=192.168.1.203
maven ansible_host=192.168.1.204
tomcat ansible_host=192.168.1.205
dovecot ansible_host=192.168.1.206
kdc ansible_host=192.168.1.207
ansible ansible_host=192.168.1.208
analyzer ansible_host=192.168.1.209
squid ansible_host=192.168.1.210
openldap ansible_host=192.168.1.211
apache ansible_host=192.168.1.212
nginx ansible_host=192.168.1.213
openvpn ansible_host=192.168.1.214
bastion ansible_host=192.168.1.216
bacula ansible_host=192.168.1.217

[dns]
dns1
dns2

[common]
analyzer
ansible
apache
bacula
bastion
dns1
dns2
dovecot
kdc
maven
nginx
nas-san
openldap
openvpn
squid
tomcat
vsftp

[nslcd_client]
analyzer
ansible
bacula
dns1
dns2
dovecot
kdc
maven
nas-san
openvpn
squid
tomcat
vsftp

[nslcd_guest]
apache

[sssd_client]
bastion

[sssd_guest]
nginx

[stunnel4_client]
kdc
tomcat
openldap
bastion

[unbound_client]
analyzer
ansible
apache
bacula
bastion
dovecot
kdc
maven
nginx
nas-san
openldap
openvpn
squid
tomcat
