---
- name: Copy CA
  ansible.builtin.copy:
    src: 'files/vagrant_ca.crt'
    dest: '/usr/local/share/ca-certificates/'
    mode: '0644'
  changed_when: false

- name: Trust CA
  ansible.builtin.shell:
    cmd: 'update-ca-certificates'
