- import_playbook: playbooks/disconnect_eth0_and_set_squid_as_default_route.yml
- import_playbook: playbooks/update_root_password.yml
- import_playbook: playbooks/update_tty_access_rules.yml
- import_playbook: playbooks/ensure_dns1_and_dns2_and_vsftp_default_resolver_correct.yml
- import_playbook: playbooks/ensure_vagrant_not_mount.yml
