---
- hosts: [active]
  gather_subset: min
  vars_files:
    - vars/dummy_root_secrets.yml
  tasks:
    - name: Update root password
      ansible.builtin.shell:
        cmd: 'echo "root:{{ root_password }}" | sudo chpasswd'
      no_log: true
