pid = /run/stunnel.pid
debug = 7
output = /var/log/stunnel4/stunnel.log

[squid-tls]
accept = 443
connect = 127.0.0.1:3128
cert = /etc/ssl/localcerts/vagrant_squid-stunnel4-server.crt
key = /etc/ssl/localcerts/vagrant_squid-stunnel4-server.key
CAfile = /usr/local/share/ca-certificates/vagrant_ca.crt
sslVersion = TLSv1.3
