[general]
pipefs-directory=/run/rpc_pipefs
[nfsrahead]
[exports]
[exportfs]
[gssd]
[lockd]
[exportd]
[mountd]
manage-gids=y
port=25000
[nfsdcld]
[nfsdcltrack]
[nfsd]
threads = 16
[statd]
[sm-notify]
[svcgssd]
