pid = /run/stunnel.pid
debug = 7
output = /var/log/stunnel4/stunnel.log

[nfs-apache]
accept = nas-san.vagrant-dummy-ops.lab:2363
connect = 127.0.0.2:2049
local = 127.0.0.2
cert = /etc/ssl/localcerts/vagrant_nas-san.crt
key = /etc/ssl/localcerts/vagrant_nas-san.key
CAfile = /etc/stunnel/ca-certs.pem
verify = 2
checkHost = apache.vagrant-dummy-ops.lab

[nfs-tomcat]
accept = nas-san.vagrant-dummy-ops.lab:2364
connect = 127.0.0.3:2049
local = 127.0.0.3
cert = /etc/ssl/localcerts/vagrant_nas-san.crt
key = /etc/ssl/localcerts/vagrant_nas-san.key
CAfile = /etc/stunnel/ca-certs.pem
verify = 2
checkHost = tomcat.vagrant-dummy-ops.lab

[nfs-kdc]
accept = nas-san.vagrant-dummy-ops.lab:2365
connect = 127.0.0.4:2049
local = 127.0.0.4
cert = /etc/ssl/localcerts/vagrant_nas-san.crt
key = /etc/ssl/localcerts/vagrant_nas-san.key
CAfile = /etc/stunnel/ca-certs.pem
verify = 2
checkHost = kdc.vagrant-dummy-ops.lab
checkHost = bastion.vagrant-dummy-ops.lab
checkHost = openldap.vagrant-dummy-ops.lab
